spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/ssafydb
    username: root
    password: ssafy
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
#    hibernate:
#       ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace


jwt:
  secret-key: a3f62325a07a3194531c43a4fb97e85d8c635959ff92bf833bd86a98a5c2cbe02a3f082a5058712221c8e7cac9ad5143ed3f6d3bce64ef052b2df2bd95a0132c

file:
  upload-dir: C:\Users\SSAFY\Documents\uploads
  max-file-size: 5MB

oauth:
  kakao:
    client-id: 4748a59e12003074b3681b074013b84d
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
  naver:
    client-id: ISnINdg5vxbmmrhbZ2rJ
    url:
      auth: https://nid.naver.com
      api: https://openapi.naver.com

springdoc:
  packages-to-scan: com.example.demo
  # consumes: request, produces: response
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    tags-sorter: alpha
    operations-sorter: method
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true