spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/ssafydb
    username: root
    password: ssafy
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace

jwt:
  # OpenSSL? 128?? 16?? ?? ?? (64Bytes)
  secret-key: a3f62325a07a3194531c43a4fb97e85d8c635959ff92bf833bd86a98a5c2cbe02a3f082a5058712221c8e7cac9ad5143ed3f6d3bce64ef052b2df2bd95a0132c

oauth:
  kakao:
    client-id: 4748a59e12003074b3681b074013b84d
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
  naver:
    secret: Zc1XDYhfgo
    client-id: ISnINdg5vxbmmrhbZ2rJ
    url:
      auth: https://nid.naver.com
      api: https://openapi.naver.com