spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
#    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    # password는 앱 비밀번호 값이며 기존 구글 비밀번호와는 다른 값임
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
        mime:
          charset: UTF-8
        transport:
          protocol: smtp

logging.level:
  org.hibernate.SQL: debug
  level:
    root: INFO
#  org.hibernate.type: trace

jwt:
  secret-key: ${JWT_SECRET_KEY}

file:
  upload-dir: C:\Users\SSAFY\Documents\uploads
  max-file-size: 5MB

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
  naver:
    client-id: ${NAVER_CLIENT_ID}
    url:
      auth: https://nid.naver.com
      api: https://openapi.naver.com

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2

app:
  awsServices:
    bucketName: ssafyd102

springdoc:
  packages-to-scan: com.ssafy.dmobile
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    tags-sorter: alpha
    operations-sorter: method
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true
