#server:
#  port: 443
#  ssl:
#    enabled: true
#    key-store: classpath:ssl/certificate.p12
#    key-store-password: "0125"
#    key-store-type: PKCS12
spring:
  datasource:
    url: jdbc:mariadb://i10d102.p.ssafy.io:3306/test
    username: root
    password: "0125"
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
    logging.level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace
